name: test-environment
channels:
  - conda-forge
dependencies:
  - xarray
  - dask
  - distributed
  - toolz
  - Cython
  - sphinx
  - pillow
  - coveralls
  - coverage
  - codecov
  - rasterio
  - libtiff
  - pyproj
  - pyresample
  - pytest
  - pytest-cov
  - fsspec
  - pip
